import type { Metadata } from "next";
import { Antic, DM_Serif_Display, Dekko } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Image from "next/image";
import bg from "@/images/background.svg";

const dm = DM_Serif_Display({
  weight: "400",
  style: "normal",
  display: "swap",
  variable: "--font-dm-serif-display",
  subsets: ["latin"],
});

const antic = Antic({
  weight: ["400"],
  style: "normal",
  display: "swap",
  variable: "--font-antic",
  subsets: ["latin"],
});

const dekko = Dekko({
  weight: "400",
  style: "normal",
  display: "swap",
  variable: "--font-dekko",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${dm.variable} ${antic.variable} ${dekko.variable}`}>
        {/* <Image
          src={bg}
          fill
          alt="A grid of graduation caps"
          className="absolute w-full h-full z-0 opacity-30 object-cover select-none"
          draggable={false}
        /> */}
        <Navbar />
        {children}
      </body>
    </html>
  );
}
