import type { Metadata } from "next";
import { Antic, DM_Serif_Display, Raleway, Urbanist } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const dm = DM_Serif_Display({
  weight: "400",
  style: "normal",
  display: "swap",
  variable: "--font-dm-serif-display",
  subsets: ["latin"],
});

const antic = Urbanist({
  weight: "variable",
  style: "normal",
  display: "swap",
  variable: "--font-dekko",
  subsets: ["latin"],
});

const dekko = Raleway({
  weight: "variable",
  style: "normal",
  display: "swap",
  variable: "--font-antic",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${dm.variable} ${antic.variable} ${dekko.variable}`}>
        <Navbar />
        <div>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
